import { Project, ResearchItem, BlogPost, SkillCategory } from './types'

export const projects: Project[] = [
  {
    id: '1',
    title: 'AI Personal Health Assistant',
    description: 'An LLM-powered health companion that tracks vitals, answers medical questions, and gives personalized wellness recommendations.',
    longDescription: 'Built on GPT-4 with RAG architecture, this assistant ingests user health data, wearable metrics, and medical literature to deliver evidence-based insights. Features include symptom checking, medication reminders, and longitudinal health trend analysis with a vector database backend.',
    imageUrl: 'https://picsum.photos/seed/healthai/800/500',
    techStack: ['Python', 'OpenAI API', 'LangChain', 'Pinecone', 'FastAPI', 'React'],
    githubUrl: 'https://github.com',
    liveUrl: 'https://demo.example.com',
    category: 'LLM Applications',
    featured: true,
  },
  {
    id: '2',
    title: 'LLM Chat Application',
    description: 'A production-grade multi-model chat interface supporting GPT-4, Claude, and Llama with streaming responses and conversation memory.',
    longDescription: 'Full-stack chat application with model switching, streaming token output, conversation history persisted in PostgreSQL, and a Redis-based caching layer. Supports system prompt customization, temperature control, and token usage analytics.',
    imageUrl: 'https://picsum.photos/seed/llmchat/800/500',
    techStack: ['Next.js', 'TypeScript', 'OpenAI API', 'Anthropic', 'Redis', 'PostgreSQL'],
    githubUrl: 'https://github.com',
    liveUrl: 'https://demo.example.com',
    category: 'LLM Applications',
    featured: true,
  },
  {
    id: '3',
    title: 'Resume Analyzer using NLP',
    description: 'Intelligent resume parsing and scoring system using transformer models to match candidates to job descriptions with explainable AI.',
    longDescription: 'Uses fine-tuned BERT for entity extraction (skills, education, experience) and a cosine similarity pipeline against job description embeddings. Provides a match score, skill gap analysis, and actionable improvement suggestions. Deployed as a REST API with a React frontend.',
    imageUrl: 'https://picsum.photos/seed/resumeai/800/500',
    techStack: ['Python', 'HuggingFace', 'BERT', 'FastAPI', 'React', 'Docker'],
    githubUrl: 'https://github.com',
    liveUrl: 'https://demo.example.com',
    category: 'NLP',
    featured: false,
  },
  {
    id: '4',
    title: 'AI Career Recommendation System',
    description: 'Personalized career path engine using collaborative filtering and LLM reasoning to suggest roles, skills, and learning resources.',
    longDescription: 'Combines matrix factorization for collaborative filtering with an LLM layer for natural language career advice. Ingests user profile data, current skills, and market salary trends from live APIs. Generates a 3-month upskilling roadmap and tracks progress.',
    imageUrl: 'https://picsum.photos/seed/careerml/800/500',
    techStack: ['Python', 'PyTorch', 'LangChain', 'OpenAI', 'Next.js', 'Supabase'],
    githubUrl: 'https://github.com',
    liveUrl: 'https://demo.example.com',
    category: 'ML Systems',
    featured: true,
  },
  {
    id: '5',
    title: 'Real-Time Image Classifier',
    description: 'Browser-based CNN classifier using TensorFlow.js that identifies 1000+ object classes from webcam or uploaded images in real time.',
    longDescription: 'Ported MobileNetV3 to TensorFlow.js with custom quantization for <2MB bundle size. Achieves 30fps inference on mid-range devices. Features confidence heatmaps via Grad-CAM visualization, top-5 predictions with probability bars, and a custom fine-tuning mode for user-defined classes.',
    imageUrl: 'https://picsum.photos/seed/imgclass/800/500',
    techStack: ['TensorFlow.js', 'React', 'TypeScript', 'MobileNet', 'WebWorkers'],
    githubUrl: 'https://github.com',
    liveUrl: 'https://demo.example.com',
    category: 'Computer Vision',
    featured: false,
  },
  {
    id: '6',
    title: 'Autonomous Research Agent',
    description: 'Multi-step AI agent that browses the web, reads papers, and synthesizes research reports using tool-calling and chain-of-thought reasoning.',
    longDescription: 'Built with LangGraph for stateful agent orchestration. The agent uses Tavily for web search, ArXiv API for paper retrieval, and a custom summarization chain to produce structured reports. Supports human-in-the-loop checkpoints, parallel tool execution, and exportable PDF reports.',
    imageUrl: 'https://picsum.photos/seed/aiagent/800/500',
    techStack: ['Python', 'LangGraph', 'LangChain', 'OpenAI', 'Tavily', 'FastAPI'],
    githubUrl: 'https://github.com',
    liveUrl: 'https://demo.example.com',
    category: 'AI Agents',
    featured: true,
  },
]

export const researchItems: ResearchItem[] = [
  {
    id: 'r1',
    title: 'Fine-tuning LLaMA 2 on Domain-Specific Data',
    description: 'Experiments with LoRA adapters and QLoRA quantization to fine-tune 7B and 13B parameter models on medical and legal corpora with limited GPU budget.',
    type: 'Experiment',
    date: '2024-11-15',
    tags: ['LLaMA', 'LoRA', 'Fine-tuning', 'QLoRA'],
    notebookUrl: 'https://github.com',
  },
  {
    id: 'r2',
    title: 'Benchmarking RAG Architectures',
    description: 'Comparative analysis of naive RAG vs. advanced RAG (HyDE, multi-query, reranking) across 5 knowledge-intensive QA datasets measuring precision, recall, and latency.',
    type: 'Research',
    date: '2024-10-02',
    tags: ['RAG', 'LangChain', 'Benchmarking', 'NLP'],
    notebookUrl: 'https://github.com',
  },
  {
    id: 'r3',
    title: 'Diffusion Model for Synthetic Data Generation',
    description: 'Training a DDPM from scratch on tabular health data to generate synthetic patient records for ML model training without privacy risks.',
    type: 'Experiment',
    date: '2024-08-20',
    tags: ['Diffusion Models', 'PyTorch', 'Synthetic Data', 'Privacy'],
    notebookUrl: 'https://github.com',
  },
  {
    id: 'r4',
    title: 'LLM Prompt Injection Attack Surface Analysis',
    description: 'Systematic evaluation of prompt injection vulnerabilities across 4 major LLM providers with a custom red-teaming framework and mitigation strategies.',
    type: 'Security',
    date: '2024-07-10',
    tags: ['LLM Security', 'Red Teaming', 'Prompt Injection'],
    notebookUrl: 'https://github.com',
  },
]

export const blogPosts: BlogPost[] = [
  {
    id: 'b1',
    title: 'Why Every AI Engineer Should Learn RAG Before Prompt Engineering',
    excerpt: "Retrieval-Augmented Generation is the single most impactful architecture pattern for production LLM apps. Here's why it outperforms prompt-only approaches at scale.",
    date: '2024-12-01',
    readTime: 7,
    tags: ['RAG', 'LLMs', 'Production AI'],
    imageUrl: 'https://picsum.photos/seed/blog1/800/400',
  },
  {
    id: 'b2',
    title: 'The Hidden Cost of Over-Engineering ML Pipelines',
    excerpt: "After building ML systems at three startups, I've learned that complexity kills velocity. Here's how to keep your ML infrastructure lean and deployable.",
    date: '2024-11-10',
    readTime: 5,
    tags: ['MLOps', 'Engineering', 'Startups'],
    imageUrl: 'https://picsum.photos/seed/blog2/800/400',
  },
  {
    id: 'b3',
    title: 'Building LLM Agents That Actually Work in Production',
    excerpt: "Most LLM agent demos fail outside the demo environment. Here's a battle-tested framework for building reliable, observable, and interruptible agents.",
    date: '2024-10-22',
    readTime: 9,
    tags: ['AI Agents', 'LangGraph', 'Production'],
    imageUrl: 'https://picsum.photos/seed/blog3/800/400',
  },
  {
    id: 'b4',
    title: 'Vector Databases Compared: Pinecone vs Weaviate vs pgvector',
    excerpt: 'A hands-on benchmark of three leading vector databases across insertion speed, query latency, recall accuracy, and operational complexity at different scales.',
    date: '2024-09-15',
    readTime: 11,
    tags: ['Vector DB', 'Pinecone', 'pgvector', 'Performance'],
    imageUrl: 'https://picsum.photos/seed/blog4/800/400',
  },
]

export const skillCategories: SkillCategory[] = [
  {
    id: 's1',
    category: 'AI / ML',
    color: 'violet',
    icon: 'Brain',
    skills: ['Machine Learning', 'Deep Learning', 'NLP', 'Computer Vision', 'LLM Applications', 'Reinforcement Learning'],
  },
  {
    id: 's2',
    category: 'Tools & Frameworks',
    color: 'cyan',
    icon: 'Wrench',
    skills: ['Python', 'PyTorch', 'TensorFlow', 'LangChain', 'OpenAI API', 'Vector Databases', 'HuggingFace'],
  },
  {
    id: 's3',
    category: 'Engineering',
    color: 'emerald',
    icon: 'Code2',
    skills: ['Next.js', 'TypeScript', 'Docker', 'REST APIs', 'Cloud Deployment', 'PostgreSQL', 'Redis'],
  },
]
